import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Separator } from '@/components/ui/separator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  ArrowLeft, 
  Download, 
  MessageSquare, 
  CheckCircle2, 
  Clock,
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  Minus,
  Lock,
  Eye
} from 'lucide-react';
import { mockStartups } from '@/data/mockData';
import { 
  formatDate, 
  formatCurrency, 
  formatPercentage,
  formatRelativeTime 
} from '@/lib/formatters';
import { toast } from 'sonner';

const ReportDetailPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [comment, setComment] = useState('');
  const [activeTab, setActiveTab] = useState('current');

  // Mock report data - in production this would come from API
  const startup = mockStartups[0];
  const reportDate = new Date();
  const previousMonth = new Date();
  previousMonth.setMonth(previousMonth.getMonth() - 1);

  const report = {
    id,
    startupId: startup.id,
    startupName: startup.name,
    startupLogo: startup.logo,
    period: reportDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
    type: 'Monthly',
    status: 'submitted', // draft, review, submitted, finalized
    submittedDate: new Date().toISOString(),
    version: 1,
    
    // Audit metadata
    metadata: {
      lastSync: new Date().toISOString(),
      dataFreshness: 95,
      sources: ['Zoho Books', 'HubSpot', 'Jira'],
      autoGenerated: true
    },
    
    // Executive Summary
    executiveSummary: `${startup.name} delivered strong performance in ${reportDate.toLocaleDateString('en-US', { month: 'long' })} with ${formatPercentage(startup.metrics.growthRate, 1)}  revenue growth. The team successfully launched two major features and onboarded 5 enterprise customers. Cash runway remains healthy at ${startup.metrics.runway.toFixed(1)} months with controlled burn rate.`,
    
    // KPI Scorecard
    kpis: {
      revenue: { 
        current: startup.metrics.revenue, 
        previous: startup.metrics.revenue * 0.9, 
        change: 10 
      },
      growthRate: { 
        current: startup.metrics.growthRate, 
        previous: startup.metrics.growthRate - 3, 
        change: 3 
      },
      burn: { 
        current: startup.metrics.burn, 
        previous: startup.metrics.burn * 1.05, 
        change: -5 
      },
      runway: { 
        current: startup.metrics.runway, 
        previous: startup.metrics.runway - 1, 
        change: 1 
      },
      headcount: { 
        current: startup.metrics.headcount, 
        previous: startup.metrics.headcount - 2, 
        change: 2 
      }
    },
    
    // Material Changes
    materialChanges: [
      'Revenue grew 10% month-over-month driven by enterprise expansion',
      'Closed 5 new enterprise deals with average ACV of $50K',
      'Burn rate decreased 5% through operational efficiency improvements',
      'Headcount increased by 2 with key engineering hires',
      'Product release cycle improved from 3 weeks to 2 weeks'
    ],
    
    // Financial Summary
    financial: {
      revenue: startup.metrics.revenue,
      revenueGrowth: startup.metrics.growthRate,
      grossMargin: startup.businessModel === 'SaaS' ? startup.metrics.grossMargin : null,
      netBurn: startup.metrics.netBurn,
      cashBalance: startup.metrics.cash,
      runway: startup.metrics.runway,
      collections: 'On track - 95% of invoices collected within 30 days'
    },
    
    // GTM Summary
    gtm: startup.businessModel === 'SaaS' ? {
      newCustomers: 8,
      churnedCustomers: 1,
      nrr: startup.metrics.nrr,
      pipelineCoverage: '3.2x',
      avgDealSize: 45000,
      salesCycle: '45 days',
      winRate: '32%'
    } : null,
    
    // Product & Execution Summary
    product: {
      releasesShipped: 2,
      featuresDeployed: 12,
      criticalBugs: 3,
      uptime: '99.8%',
      userGrowth: '15%',
      engagement: 'DAU increased 12% with new feature adoption at 65%'
    },
    
    // Risks and Asks
    risks: [
      { 
        severity: 'medium', 
        title: 'Sales pipeline velocity', 
        description: 'Enterprise sales cycle lengthened by 10 days. Implementing new qualification process.' 
      },
      { 
        severity: 'low', 
        title: 'Engineering capacity', 
        description: 'Team at 90% utilization. Planning Q2 hiring to scale.' 
      }
    ],
    
    asks: [
      'Introduction to VP Sales at Fortune 500 companies in healthcare',
      'Guidance on enterprise pricing strategy',
      'Connect with technical co-founder candidates'
    ],
    
    // Founder Note
    founderNote: `This was a strong month of execution. The team is firing on all cylinders and customer feedback has been overwhelmingly positive. We're seeing strong product-market fit signals with organic referrals increasing 40%. Focus for next month: accelerating enterprise pipeline and scaling the engineering team.`,
    
    // Comments
    comments: [
      {
        id: 'comment-1',
        author: 'Sarah Chen',
        role: 'Partner',
        content: 'Excellent progress on revenue growth. Would love to discuss the enterprise pricing strategy in our next board meeting.',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
      }
    ]
  };

  const handleAddComment = () => {
    if (!comment.trim()) return;
    toast.success('Comment added', {
      description: 'Founder will be notified'
    });
    setComment('');
  };

  const handleFinalizeReport = () => {
    toast.success('Report finalized', {
      description: 'Report has been locked and archived'
    });
  };

  const getTrendIcon = (change) => {
    if (change > 0) return <TrendingUp className="h-4 w-4 text-success" />;
    if (change < 0) return <TrendingDown className="h-4 w-4 text-destructive" />;
    return <Minus className="h-4 w-4 text-muted-foreground" />;
  };

  const getStatusBadge = (status) => {
    const variants = {
      draft: { variant: 'outline', icon: Clock, color: 'text-muted-foreground' },
      review: { variant: 'outline', icon: Eye, color: 'text-warning' },
      submitted: { variant: 'default', icon: CheckCircle2, color: 'text-primary' },
      finalized: { variant: 'default', icon: Lock, color: 'text-success' }
    };
    const config = variants[status] || variants.draft;
    const Icon = config.icon;
    
    return (
      <Badge variant={config.variant} className="gap-1">
        <Icon className={`h-3 w-3 ${config.color}`} />
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </Badge>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-4">
          <Button 
            onClick={() => navigate('/reports')} 
            variant="outline" 
            size="icon"
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex items-start gap-4">
            <img 
              src={report.startupLogo} 
              alt={report.startupName} 
              className="h-12 w-12 rounded-lg border"
            />
            <div>
              <div className="flex items-center gap-3 mb-1">
                <h1 className="text-2xl font-semibold">{report.type} Report</h1>
                {getStatusBadge(report.status)}
              </div>
              <div className="flex items-center gap-3 text-sm text-muted-foreground">
                <span>{report.startupName}</span>
                <span>•</span>
                <span>{report.period}</span>
                <span>•</span>
                <span>Version {report.version}</span>
              </div>
            </div>
          </div>
        </div>
        
        <div className="flex gap-2">
          <Button variant="outline">
            <Download className="h-4 w-4 mr-2" />
            Export PDF
          </Button>
          {report.status === 'submitted' && (
            <Button onClick={handleFinalizeReport}>
              <Lock className="h-4 w-4 mr-2" />
              Finalize Report
            </Button>
          )}
        </div>
      </div>

      {/* Audit Metadata */}
      <Card className="border-primary/30 bg-primary/5">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-6 text-sm">
              <div>
                <span className="text-muted-foreground">Last Sync:</span>
                <span className="ml-2 font-medium">{formatRelativeTime(report.metadata.lastSync)}</span>
              </div>
              <div>
                <span className="text-muted-foreground">Data Freshness:</span>
                <span className="ml-2 font-medium">{report.metadata.dataFreshness}%</span>
              </div>
              <div>
                <span className="text-muted-foreground">Sources:</span>
                <span className="ml-2 font-medium">{report.metadata.sources.join(', ')}</span>
              </div>
              {report.metadata.autoGenerated && (
                <Badge variant="outline">
                  <CheckCircle2 className="h-3 w-3 mr-1" />
                  Auto-Generated
                </Badge>
              )}
            </div>
            <div className="text-sm text-muted-foreground">
              Submitted {formatRelativeTime(report.submittedDate)}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tabs for Current vs History */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="current">Current Report</TabsTrigger>
          <TabsTrigger value="history">Version History</TabsTrigger>
        </TabsList>

        <TabsContent value="current" className="space-y-6 mt-6">
          {/* Executive Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Executive Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground leading-relaxed">{report.executiveSummary}</p>
            </CardContent>
          </Card>

          {/* KPI Scorecard */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">KPI Scorecard</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-4">
                {Object.entries(report.kpis).map(([key, data]) => (
                  <div key={key} className="p-4 border rounded-lg">
                    <p className="text-sm text-muted-foreground mb-1 capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</p>
                    <div className="flex items-baseline gap-2 mb-1">
                      <p className="text-2xl font-semibold tabular-nums">
                        {key.includes('Rate') || key.includes('Growth') 
                          ? formatPercentage(data.current, 1)
                          : key === 'revenue' || key === 'burn'
                          ? formatCurrency(data.current, true)
                          : data.current.toFixed(1)}
                      </p>
                      <div className="flex items-center gap-1">
                        {getTrendIcon(data.change)}
                        <span className={`text-sm font-medium ${
                          data.change > 0 ? 'text-success' : 
                          data.change < 0 ? 'text-destructive' : 
                          'text-muted-foreground'
                        }`}>
                          {formatPercentage(Math.abs(data.change), 0)}
                        </span>
                      </div>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      vs {key.includes('Rate') || key.includes('Growth')
                        ? formatPercentage(data.previous, 1)
                        : key === 'revenue' || key === 'burn'
                        ? formatCurrency(data.previous, true)
                        : data.previous.toFixed(1)}
                    </p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Material Changes */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">What Changed Materially</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {report.materialChanges.map((change, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <CheckCircle2 className="h-5 w-5 text-success shrink-0 mt-0.5" />
                    <span className="text-foreground">{change}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Financial Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Financial Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-semibold mb-3">Key Metrics</h4>
                  <div className="space-y-3">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Revenue</span>
                      <span className="font-semibold tabular-nums">{formatCurrency(report.financial.revenue, true)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Revenue Growth</span>
                      <span className="font-semibold tabular-nums text-success">
                        {formatPercentage(report.financial.revenueGrowth, 1, true)}
                      </span>
                    </div>
                    {report.financial.grossMargin && (
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Gross Margin</span>
                        <span className="font-semibold tabular-nums">{formatPercentage(report.financial.grossMargin)}</span>
                      </div>
                    )}
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Net Burn</span>
                      <span className="font-semibold tabular-nums">{formatCurrency(report.financial.netBurn, true)}</span>
                    </div>
                  </div>
                </div>
                <div>
                  <h4 className="font-semibold mb-3">Cash Position</h4>
                  <div className="space-y-3">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Cash Balance</span>
                      <span className="font-semibold tabular-nums">{formatCurrency(report.financial.cashBalance, true)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Runway</span>
                      <span className="font-semibold tabular-nums">{report.financial.runway.toFixed(1)} months</span>
                    </div>
                    <div className="pt-2 border-t">
                      <p className="text-sm text-muted-foreground">{report.financial.collections}</p>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* GTM Summary (if applicable) */}
          {report.gtm && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">GTM Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">New Customers</p>
                    <p className="text-2xl font-semibold">{report.gtm.newCustomers}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Churned</p>
                    <p className="text-2xl font-semibold">{report.gtm.churnedCustomers}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">NRR</p>
                    <p className="text-2xl font-semibold">{formatPercentage(report.gtm.nrr)}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Pipeline Coverage</p>
                    <p className="text-2xl font-semibold">{report.gtm.pipelineCoverage}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Avg Deal Size</p>
                    <p className="text-2xl font-semibold">{formatCurrency(report.gtm.avgDealSize, true)}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Sales Cycle</p>
                    <p className="text-2xl font-semibold">{report.gtm.salesCycle}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Win Rate</p>
                    <p className="text-2xl font-semibold">{report.gtm.winRate}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Product & Execution Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Product & Execution Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Releases Shipped</p>
                  <p className="text-2xl font-semibold">{report.product.releasesShipped}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Features Deployed</p>
                  <p className="text-2xl font-semibold">{report.product.featuresDeployed}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Critical Bugs</p>
                  <p className="text-2xl font-semibold">{report.product.criticalBugs}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Uptime</p>
                  <p className="text-2xl font-semibold">{report.product.uptime}</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground border-t pt-4">{report.product.engagement}</p>
            </CardContent>
          </Card>

          {/* Risks and Asks */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Risks</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {report.risks.map((risk, idx) => (
                    <div key={idx} className="flex gap-3">
                      <AlertTriangle className={`h-5 w-5 shrink-0 mt-0.5 ${
                        risk.severity === 'high' ? 'text-destructive' :
                        risk.severity === 'medium' ? 'text-warning' :
                        'text-muted-foreground'
                      }`} />
                      <div>
                        <p className="font-medium mb-1">{risk.title}</p>
                        <p className="text-sm text-muted-foreground">{risk.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Asks</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {report.asks.map((ask, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="text-primary font-semibold shrink-0">{idx + 1}.</span>
                      <span className="text-foreground">{ask}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Founder Note */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Founder Note</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground leading-relaxed italic">"{report.founderNote}"</p>
            </CardContent>
          </Card>

          <Separator />

          {/* Comments Section */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Investor Comments</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {report.comments.map(c => (
                <div key={c.id} className="border-l-2 border-primary pl-4 py-2">
                  <div className="flex items-center gap-2 mb-2">
                    <p className="font-semibold">{c.author}</p>
                    <Badge variant="outline" className="text-xs">{c.role}</Badge>
                    <span className="text-xs text-muted-foreground">{formatRelativeTime(c.timestamp)}</span>
                  </div>
                  <p className="text-sm text-foreground">{c.content}</p>
                </div>
              ))}
              
              <div className="pt-4 border-t">
                <Textarea
                  placeholder="Add a comment or question..."
                  value={comment}
                  onChange={(e) => setComment(e.target.value)}
                  className="mb-2"
                />
                <Button onClick={handleAddComment}>
                  <MessageSquare className="h-4 w-4 mr-2" />
                  Add Comment
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="history" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Version History</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <div className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex items-center gap-3">
                    <Badge>v{report.version}</Badge>
                    <div>
                      <p className="font-medium">Current Version</p>
                      <p className="text-sm text-muted-foreground">
                        Submitted {formatDate(report.submittedDate)}
                      </p>
                    </div>
                  </div>
                  {getStatusBadge(report.status)}
                </div>
                
                <div className="flex items-center justify-between p-4 border rounded-lg opacity-50">
                  <div className="flex items-center gap-3">
                    <Badge variant="outline">v{report.version - 1}</Badge>
                    <div>
                      <p className="font-medium">Previous Version</p>
                      <p className="text-sm text-muted-foreground">
                        Finalized {formatDate(previousMonth.toISOString())}
                      </p>
                    </div>
                  </div>
                  {getStatusBadge('finalized')}
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default ReportDetailPage;